### ISSUE TITLE
出现TypeError: 'type' object is not subscriptable`

### ISSUE THREAD

**Issue by MyuriKanao** [EmiyaGm/nonebot-plugin-lostark-wandering-trader#2]
这边用的zhenxunbot
Python 3.8.10

以下是日志

`08-05 21:40:01 [ERROR] nonebot | Failed to import "nonebot_plugin_lostark_wandering_trader"
Traceback (most recent call last):

  File "bot.py", line 16, in <module>
    nonebot.load_plugins("my_plugins")
    │       └ <function load_plugins at 0x7f557d537160>
    └ <module 'nonebot' from '/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/noneb...

  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f557d52d9d0>
           └ PluginManager(plugins=set(), search_path={'my_plugins'})
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
                  │    │           │         │       │    └ <property object at 0x7f557d527900>
                  │    │           │         │       └ PluginManager(plugins=set(), search_path={'my_plugins'})
                  │    │           │         └ 'nonebot_plugin_lostark_wandering_trader'
                  │    │           └ 'nonebot_plugin_lostark_wandering_trader'
                  │    └ <function PluginManager.load_plugin at 0x7f557d52d940>
                  └ PluginManager(plugins=set(), search_path={'my_plugins'})
> File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f557ea55820>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'my_plugins.nonebot_plugin_lostark_wandering_trader'
           │          └ <function _gcd_import at 0x7f557eb6f430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
                        └ <module 'my_plugins.nonebot_plugin_lostark_wandering_trader' from '/home/ubuntu/zhenxun_bot/my_plugins/nonebot_plugin_lostark...
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/home/ubuntu/zhenxun_bot/my_plugins/nonebot_plugin_lostark_wandering_trader/__init__.py", line 9, in <module>
    from .config import Config

  File "/home/ubuntu/zhenxun_bot/my_plugins/nonebot_plugin_lostark_wandering_trader/config.py", line 4, in <module>
    class ScopedConfig(BaseModel):
                       └ <class 'pydantic.main.BaseModel'>

  File "/home/ubuntu/zhenxun_bot/my_plugins/nonebot_plugin_lostark_wandering_trader/config.py", line 5, in ScopedConfig
    user_ids: list[int] = []
    └ []

TypeError: 'type' object is not subscriptable`

**Comment by EmiyaGm** [comment]
您是用什么方式安装的这个插件

**Comment by MyuriKanao** [comment]
> 您是用什么方式安装的这个插件

pip install nonebot-plugin-lostark-wandering-trader

**Comment by EmiyaGm** [comment]
> 

您可以看一下插件版本，如果是 0.0.3 这个版本的话，得预先填入相关配置，不然在获取 config 的时候会报错，或者您可以稍微等一下我的版本更新，后续版本已经修复了这个问题

**Comment by EmiyaGm** [comment]
> > 您是用什么方式安装的这个插件
> 
> pip install nonebot-plugin-lostark-wandering-trader

插件更新到 0.0.6 版本，你可以安装试一下

**Comment by MyuriKanao** [comment]
恩，我暂时使用的是0.0.3。我修改了config.py，

> from pydantic import BaseModel
from typing import List


class ScopedConfig(BaseModel):
    user_ids: List[int] = []
    group_ids: List[int] = []
    time: int = 1
    server_id: int = 14
    rarity: List[str] = []
    send_type: List[str] = []


class Config(BaseModel):
    trader: ScopedConfig


class PluginMetadata:
    def __init__(self, **metadata):
        self.__dict__.update(metadata)
        self.type = metadata.get("type", "")
        self.homepage = metadata.get("homepage", "")


最后解决了这个问题
